name: Test Deployment

on:
  push:
    branches:
      # - main
      # - main--test-deploy

jobs:
  push:
    name: Push
    runs-on: ubuntu-latest
    steps:
    - name: SSH
      uses: appleboy/ssh-action@v0.1.8
      with:
        host: ${{ secrets.TEST_SERVER_HOST }}
        username: ${{ secrets.TEST_SERVER_USERNAME }}
        key: ${{ secrets.TEST_SERVER_KEY }}
        port: ${{ secrets.TEST_SERVER_PORT }}
        # script: sudo bash -c "cd /ssd2/projects/diginext/diginext-new-backend/modules/tech-studio/lms-module && git pull origin main && bash .github/workflows/test-deploy.bash"
